server:
  port: 9000
  shutdown: graceful

spring:
  application:
    name: user-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/CourseRealm}

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URI:http://localhost:8080}
  realm: CourseRealm
  resource: user-management
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET_USER:Y4zXYewUrHxbigRv8y82mpDsyW3fpD4B}
