
#  Use this file to store the Kubernetes Pod manifests for the application.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers: # The list of containers in the Pod
        - name: user-service
          image: user-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
