name: Build and Push Stage (CI)
on:
  push:
    branches: ["main"]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: online-language-learning-system/user-service
  VERSION: latest
jobs:
  package:
    runs-on: ubuntu-22.04
    outputs:
      jar-path: ${{ steps.build-jar.outputs.jar }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK17 
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Build JAR
        run: mvn clean pacakge -DskipTests
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar
  build:
    runs-on: ubuntu-22.04
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-file
          path: target/
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} .
      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}